USE DATABASE WALMART_DEV;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT CSV_FF
TYPE='CSV'
FIELD_DELIMITER=','
SKIP_HEADER=1
FIELD_OPTIONALLY_ENCLOSED_BY='"'
DATE_FORMAT='AUTO'
NULL_IF = ('NA', 'null', '');

CREATE OR REPLACE STAGE WALMART_STAGE
STORAGE_INTEGRATION = walmart_s3_int
URL = 's3://walmart-pipeline-raw-manual/'
FILE_FORMAT = CSV_FF;

LIST @WALMART_STAGE;