USE DATABASE WALMART_DEV;
USE SCHEMA WALMART_DEV.RAW;


CREATE OR REPLACE PIPE STORES_PIPE
    AUTO_INGEST=TRUE
AS
COPY INTO STORES_RAW (store_id, store_type, store_size, _file_name, _row_number)
FROM(
    SELECT $1, $2, $3, METADATA$FILENAME, METADATA$FILE_ROW_NUMBER
    FROM @WALMART_STAGE/stores/
)
FILE_FORMAT=(FORMAT_NAME=CSV_FF)
ON_ERROR=CONTINUE;

CREATE OR REPLACE PIPE DEPARTMENT_PIPE
    AUTO_INGEST=TRUE
AS
COPY INTO DEPARTMENT_RAW(store_id, dept_id, date, weekly_sales, is_holiday, _file_name, _row_number)
FROM(
    SELECT $1, $2, $3, $4, $5, METADATA$FILENAME, METADATA$FILE_ROW_NUMBER
    FROM @WALMART_STAGE/departments/
)
FILE_FORMAT=(FORMAT_NAME=CSV_FF)
ON_ERROR=CONTINUE;

CREATE OR REPLACE PIPE FACT_PIPE
    AUTO_INGEST=TRUE
AS
COPY INTO FACT_RAW(store_id, date, temperature, fuel_price, markdown1, markdown2, markdown3,
   markdown4, markdown5, cpi, unemployment, is_holiday, _file_name, _row_number)
FROM (
    SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,
         METADATA$FILENAME, METADATA$FILE_ROW_NUMBER
  FROM @WALMART_STAGE/fact/
)
FILE_FORMAT=(FORMAT_NAME = CSV_FF)
ON_ERROR = CONTINUE;


DESC PIPE STORES_PIPE;
DESC PIPE FACT_PIPE;
DESC PIPE DEPARTMENT_PIPE;