-- Role creation and role-to-user grants are a SECURITYADMIN concern in
-- Snowflake's standard hierarchy; object/warehouse grants are a SYSADMIN
-- concern (SYSADMIN owns the database/warehouses created earlier). If
-- you're on a trial account and have been running everything as
-- ACCOUNTADMIN so far, that's fine too - just run the whole file as
-- ACCOUNTADMIN instead of switching roles mid-script.

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS WALMART_LOADER;
CREATE ROLE IF NOT EXISTS WALMART_TRANSFORMER;
CREATE ROLE IF NOT EXISTS WALMART_REPORTER;

-- Functional roles report up to SYSADMIN so they sit in the normal admin
-- tree instead of floating disconnected from it.
GRANT ROLE WALMART_LOADER TO ROLE SYSADMIN;
GRANT ROLE WALMART_TRANSFORMER TO ROLE SYSADMIN;
GRANT ROLE WALMART_REPORTER TO ROLE SYSADMIN;

-- For now, grant all three to your own user so you can test as each one
-- (USE ROLE WALMART_REPORTER; SELECT ...). Once dbt and Airflow exist,
-- WALMART_LOADER and WALMART_TRANSFORMER move to dedicated service users
-- instead of your personal login.
GRANT ROLE WALMART_LOADER TO USER AYLIN1216;
GRANT ROLE WALMART_TRANSFORMER TO USER AYLIN1216;
GRANT ROLE WALMART_REPORTER TO USER AYLIN1216;

GRANT USAGE ON WAREHOUSE LOAD_WH TO ROLE WALMART_LOADER;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE WALMART_TRANSFORMER;
GRANT USAGE ON WAREHOUSE REPORT_WH TO ROLE WALMART_REPORTER;


USE ROLE SYSADMIN;
 
-- LOADER: write into RAW only, nothing else
GRANT USAGE ON DATABASE WALMART_DEV TO ROLE WALMART_LOADER;
GRANT USAGE ON SCHEMA WALMART_DEV.RAW TO ROLE WALMART_LOADER;
GRANT INSERT ON ALL TABLES IN SCHEMA WALMART_DEV.RAW TO ROLE WALMART_LOADER;
GRANT INSERT ON FUTURE TABLES IN SCHEMA WALMART_DEV.RAW TO ROLE WALMART_LOADER;
GRANT USAGE ON INTEGRATION walmart_s3_int TO ROLE WALMART_LOADER;



-- TRANSFORMER: read RAW, full read/write on SILVER and GOLD (this is the
-- role dbt runs as)
GRANT USAGE ON DATABASE WALMART_DEV TO ROLE WALMART_TRANSFORMER;
 
GRANT USAGE ON SCHEMA WALMART_DEV.RAW TO ROLE WALMART_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA WALMART_DEV.RAW TO ROLE WALMART_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA WALMART_DEV.RAW TO ROLE WALMART_TRANSFORMER;
 
GRANT USAGE ON SCHEMA WALMART_DEV.SILVER TO ROLE WALMART_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA WALMART_DEV.SILVER TO ROLE WALMART_TRANSFORMER;
GRANT ALL ON ALL TABLES IN SCHEMA WALMART_DEV.SILVER TO ROLE WALMART_TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA WALMART_DEV.SILVER TO ROLE WALMART_TRANSFORMER;
 
GRANT USAGE ON SCHEMA WALMART_DEV.GOLD TO ROLE WALMART_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA WALMART_DEV.GOLD TO ROLE WALMART_TRANSFORMER;
GRANT ALL ON ALL TABLES IN SCHEMA WALMART_DEV.GOLD TO ROLE WALMART_TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA WALMART_DEV.GOLD TO ROLE WALMART_TRANSFORMER;
 
-- REPORTER: read-only on GOLD, nothing else - Tableau should never be
-- able to see RAW or SILVER, even by accident
GRANT USAGE ON DATABASE WALMART_DEV TO ROLE WALMART_REPORTER;
GRANT USAGE ON SCHEMA WALMART_DEV.GOLD TO ROLE WALMART_REPORTER;
GRANT SELECT ON ALL TABLES IN SCHEMA WALMART_DEV.GOLD TO ROLE WALMART_REPORTER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA WALMART_DEV.GOLD TO ROLE WALMART_REPORTER;
 
-- Note on pipe ownership: a pipe's COPY INTO runs with the privileges of
-- whichever role owns the pipe - currently SYSADMIN, since that's what
-- created it in 05_pipes.sql. WALMART_LOADER above doesn't need to own
-- the pipes for auto-ingest to keep working; it's set up for manual
-- loading/testing now and for the service account you'll point Airflow
-- at later. Transferring pipe/stage ownership to WALMART_LOADER is the
-- fuller production pattern, but isn't required to get RBAC boundaries
-- working today.

ALTER USER AYLIN1216 SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw1Su8Jl6avNkeHtsp7Ch
HNOw9tp85s9o5NDVyuPCcTTIfaA6R0NtCUpI9Q6b8+Vt+eu8PnQ+rhHY0pWwcFOz
58CXSJRM18kuqFdGqDKvkz/VCPwWoMnciFgT3MgSJ3bVCciGsGdftRUAQDQyaM8n
LC8Kjv8EKfU9MnOXYdS1MT6+kz4PF5SNa1tmR/rWcsQHydMkqDv/HpwuqFvRx/jk
aiS+mU20pEIBPCZ4XIeX0Sbl1igawuKtGhGnsvJP3J3LtgBGh9Il/bAZR+dRd/js
fKU6U1m5vdKlfuS8629H6UjKyXXsnSELvreuP6FPZlgt6eklGPLKmXTbxhfGmUbX
VQIDAQAB'

DESC USER AYLIN1216;

SHOW GRANTS TO USER AYLIN1216;